version: "3.8"

services:
  app:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
      nats-server:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 1s
      timeout: 1s
      retries: 5
    volumes:
      - ./mongodb_data:/data/db

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
    healthcheck:
      test: [ "CMD", "nats", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
