version: "3.8"

services:
  app:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=secret1
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      timeout: 5s
      retries: 10
    volumes:
      - ./mongodb_data:/data/db
