version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: localmongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 1s
      timeout: 1s
      retries: 5
    volumes:
      - ./mongodb_data:/data/db

  nats-server:
    image: nats:latest
    container_name: nats-server
    environment:
      - NATS_URL=nats://localhost:4222
    ports:
      - "4222:4222"
    healthcheck:
      test: [ "CMD", "nats", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 5

  redis:
    image: redis:latest
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  kafka-lp:
    image: confluentinc/cp-kafka:7.5.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENERS=INTERNAL://kafka-lp:29092, EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-lp:29092, EXTERNAL://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-lp:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=http://localhost:9092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://localhost:8081
    depends_on:
      - zookeeper-lp
    volumes:
      - kafka-data:/var/lib/kafka/data

  zookeeper-lp:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  schema-registry-lp:
    image: confluentinc/cp-schema-registry:7.5.1
    ports:
      - "8081:8081"
    depends_on:
      - kafka-lp
      - zookeeper-lp
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-lp:29092

volumes:
  mongo-data:
  kafka-data:
  zookeeper-data:
  zookeeper-log:
