name: Build-actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Grant execute permission for docker-compose-local.yaml
        run: chmod +x docker-compose-local

      - name: Starting services with docker-compose
        run: docker-compose -f docker-compose-local.yaml up -d

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile and run checks
        run: ./gradlew build -s
