name: Build-actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile and run checks
        run: ./gradlew assemble

      - name: Start containers
        run: docker compose -f docker-compose.yaml up --build --force-recreate -d app

      - name: Run tests
        run: ./gradlew test

      - name: Stop Docker Container
        run: docker compose down

      - name : Shutdown
        if: always()
        run: docker compose down
